FROM ubuntu:18.04

WORKDIR /copy

COPY nomeArquivo .

WORKDIR /add

ADD add-files.tar.gz .
ADD https://www.docker.com/arquivo.png .

RUN apt-get update && apt-get install -y \
    net-tools \
    curl \
    nginx \
    && rm -rf /var/lib/apt/lists/*
